<?php
declare(strict_types=1);

use Ctw\Http\Entity;
use Ctw\Http\HttpException;

// @phpstan-ignore-next-line
$entity = $this->entity;
assert($entity instanceof Entity\HttpStatus);

// @phpstan-ignore-next-line
$exception = $this->exception;
assert($exception instanceof HttpException\AbstractException);

$vars = [
    $entity,
    (object) [
        'statusCode' => $exception->getStatusCode(),
        'message'    => $exception->getMessage(),
    ],
];

echo json_encode($vars, JSON_THROW_ON_ERROR);
