<?php
declare(strict_types=1);

use Ctw\Http\Entity;
use Ctw\Http\HttpException;

/** @var Entity\HttpStatus $entity */
$entity = $this->entity;

/** @var HttpException\NotFoundException $exception */
$exception = $this->exception;

$vars = [
    $entity,
    (object) [
        'statusCode' => $exception->getStatusCode(),
        'message'    => $exception->getMessage(),
    ],
];

echo json_encode($vars, JSON_THROW_ON_ERROR);
